### ISSUE TITLE
QCM reliability

### ISSUE THREAD

**Issue by Melanie8** [obonaventure/cnp3#138]
Pour le premier exercice de la partie "Error detection and correction" de la page http://cnp3book.info.ucl.ac.be/2nd/html/mcq-ex/mcq-reliability.html, la bonne réponse est 
1010111011110101
1110101010101011
1111111011111111
0100010101011110 => parity block.
En faisant un XOR, on devrait pourtant avoir 0 (resp. 1) quand on a un nombre pair (resp. impair) de bits mis à 1. Donc le parity block devrait ici plutôt être 1011101010100001 (on inverse les 0 et les 1).

**Comment by obonaventure** [comment]
J'ai réécrit la question en mentionnant une parité paire, ce qui évite l'ambiguité du XOR.
