### ISSUE TITLE
Character Stuffing Bold on wrong words - 

### ISSUE THREAD

**Issue by fthuin** [obonaventure/cnp3#142]
Dans la partie théorie, character stuffing (into connecting two hosts -> framing) il y a un problème de mise en gras des caractères. Le texte dit qu'on enlève le **second** caractère DLE à la réception, pourtant la partie de la frame mise en gras est chaque fois le **second** caractère DLE, comme s'il appartenait à la frame originale, ce qui n'est pas le cas (ce devrait être **le premier selon l'explication**)

**Comment by obonaventure** [comment]
Exact, merci pour le commentaire.
