### ISSUE TITLE
Electronic mail - Server preference

### ISSUE THREAD

**Issue by fthuin** [obonaventure/cnp3#144]
In the ebook, electronic mail part, it is said " The DNS can return several MX records for a given domain. In this case, the server with the **lowest** preference is used first. If this server is not reachable, the second most preferred server is used etc."

Shouldn't it be "the server with the **highest** preference is used first" ?

**Comment by obonaventure** [comment]
RFC2821 contains the following in section 5:

   Multiple MX records contain a preference indication that MUST be used
   in sorting (see below).  Lower numbers are more preferred than higher
   ones.
