### ISSUE TITLE
2 simplest error detection schemes

### ISSUE THREAD

**Issue by GregoryVds** [obonaventure/cnp3#156]
In "2.1.2. Datalink Layer - Reliable data transfer on top of an imperfect link", it is said:
- "The simplest error detection code is the parity bit".
And a few lines further:
- "The simplest error detection scheme is the checksum".
I believe there is not significant difference between scheme and code, so both cannot be the simplest.

**Comment by obonaventure** [comment]
The first bullet refers to an error detection code while the second to an error detection scheme.
