### ISSUE TITLE
make latex failed on linux fedora

### ISSUE THREAD

**Issue by aktarus42** [obonaventure/cnp3#176]
Hi,
I tried to generate latex files with "make latex" command but it failed:

Markup is unsupported in LaTeX:
exercises/packetdrill:None: literal blocks in footnotes are not supported by LaTeX
Makefile:99: recipe for target 'latex' failed
make: *** [latex] Error 1

I am missing something? I'm running linux fedora 21.

**Comment by obonaventure** [comment]
I think that the problem is inside this file https://github.com/obonaventure/cnp3/blob/master/book-2nd/exercises/packetdrill.rst

Can you edit your copy and replace second footnote ?

**Comment by aktarus42** [comment]
Thanks for your reply. I removed lines 478 to 480:
.. code-block:: console

tcpdump -i any -n port port 8080

Now it compiles. However, building the PDF from latex raises path error on several figures. For example, line 317 in the latex file says:
\scalebox{0.800000}{\includegraphics{principles/../../book/intro/svg/intro-figures-027-c.png}}

There is no such directory/file in my computer. The correct path for me is:
../../../book/intro/png/intro-figures-027-c.png

I have similar errors for many figures.

**Comment by obonaventure** [comment]
I've updated the Vagrantfile and it now compiles again on the virtual box
