### ISSUE TITLE
book-2nd : Make pdfLatex failed

### ISSUE THREAD

**Issue by lechjo01** [obonaventure/cnp3#177]
Hello,

I tried to generate pdf files with **make latexpdf** command in **book-2nd** directory but it failed:

`! Incomplete \iffalse; all text was ignored after line 7552.`
`<inserted text>`
`\fi`
`<*> CNP3.tex`

Maybe it comes from my Sphinx version ?
*Sphinx version : 1.3.1.*

Thanks

**Comment by obonaventure** [comment]
Should work with the new vagrant file
