### ISSUE TITLE
Typing error

### ISSUE THREAD

**Issue by Memehd** [obonaventure/cnp3#181]
I think there is a mistake in section "The network layer". Just before the section "IP version 6", in the sentence "Unfortunately no datalink layer is able to send frames of unlimited side" . I think that is  "size" instead of "side".

Mehdi Dumoulin

**Comment by obonaventure** [comment]
On 19/08/15 14:21, Memehd wrote:
> I think there is a mistake in section "The network layer". Just before
> the section "IP version 6", in the sentence "Unfortunately no datalink
> layer is able to send frames of unlimited side" . I think that is "size"
> instead of "side".

feel free to update the text directly on github. This will cause a pull 
request that I will be able to immediately accept

Thanks

OB
